
FACEBOOK_APP_ID = "FACEBOOK_APP_ID" 
FACEBOOK_APP_SECRET = "FACEBOOK_APP_SECRET"

TWITTER_CONSUMER_KEY = "TWITTER_CONSUMER_KEY"
TWITTER_CONSUMER_SECRET_KEY = "TWITTER_CONSUMER_SECRET_KEY"


ADMIN_MAIN = "nuno.miguel.77@gmail.com"
